version: "3.8"

services:
  nginx:
    image: boys-next-door.win
    container_name: nginx
    restart: always
    build:
        context: nginx
        dockerfile: ./Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      VIRTUAL_HOST: boys-next-door.win
    volumes:
      - ./nginx/static:/app
    networks:
      - boys-next-door-network

  main-react:
    container_name: main-react
    restart: unless-stopped
    build:
      context: main-react
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    depends_on:
      - nginx
    networks:
      - boys-next-door-network

  foundry-old:
    container_name: Fvtt
    user: node
    build:
      context: foundry-old
      dockerfile: Dockerfile
    image: fvtt:3.0
    volumes:
      - ./foundry-old/app:/home/node/app
      - ./foundry-old/data:/home/node/data
    ports:
      - "30000:30001"
    environment:
      VIRTUAL_HOST: foundry.boys-next-door.win
    restart: unless-stopped
    stop_grace_period: 2m
    depends_on:
      - nginx
    networks:
      - boys-next-door-network

  foundry:
    image: felddy/foundryvtt:release
    hostname: foundry.boys-next-door.win
    restart: unless-stopped
    volumes:
      - type: bind
        source: foundry
        target: /data
    env_file:
      - ./foundry/.env
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    depends_on:
      - nginx
    networks:
      - boys-next-door-network

  valheim:
    image: ghcr.io/lloesche/valheim-server
#    cap_add:
#      - sys_nice
    volumes:
      - ${HOME}/valheim-server/config:/config
      - ${HOME}/valheim-server/data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - ${HOME}/valheim-server/valheim.env
    restart: unless-stopped
    stop_grace_period: 2m

  dis-bot:
    image: vruzhentsov/boys-next-door-dis-bot
    restart: unless-stopped
    stop_grace_period: 2m
    ports:
      - "3000:3000"
    env_file:
      - dis-bot/.env
    depends_on:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3-alpine # pin the image version to Lavalink v3
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G # set Java options here
      - SERVER_PORT=2333 # set lavalink server port
    env_file:
      - .env
    volumes:
      - ./lavalink/lavalink-application.yml:/opt/Lavalink/application.yml # mount application.yml from the same directory or use environment variables
      - ./lavalink/lava-plugins/:/opt/Lavalink/plugins/ # persist plugins between restarts, make sure to set the correct permissions (user: 322, group: 322)
    networks:
      - lavalink
    expose:
      - 2333 # lavalink exposes port 2333 to connect to for other containers (this is for documentation purposes only)
    ports:
      - 2333:2333 # you only need this if you want to make your lavalink accessible from outside of containers

  terraria-tmodloader:
    image: 'jacobsmile/tmodloader1.4:latest'
    container_name: 'tmodloader'
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download the Calamity mod and CalamityMusic mod.
      - "TMOD_AUTODOWNLOAD=2824688072,2824688266"
      # Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_ENABLEDMODS=2824688072,2824688266"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=Goodbye!"
      - "TMOD_AUTOSAVE_INTERVAL=15"
      # Server Settings
      - "TMOD_MOTD=Welcome to my tModLoader Server!"
      - "TMOD_PASS="
      - "TMOD_MAXPLAYERS=16"
      # The following world settings are only used when generating a new world.
      - "TMOD_WORLDNAME=Annoyed_Bank"
      - "TMOD_WORLDSIZE=2"
      - "TMOD_WORLDSEED=not the bees!"
      - "TMOD_DIFFICULTY=2"
      # (Deprecated) If TMOD_USECONFIGFILE is set to "Yes", it is expected to have a serverconfig.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "UPDATE_NOTICE=false"

    volumes:
      ##### By default, the below setting will create a data directory on your host where this compose file lives.
      - "./terraria:/data"
      # Uncomment the below line if you plan to use a mapped config file.
      # - "/path/to/config/config.txt:/root/terraria-server/serverconfig.txt"

  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 8123:8123
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.19.2
      ONLINE_MODE: "FALSE"
      NAME: "Boys"
      MOTD: "Next door"
      MEMORY: "4G"
      SPAWN_PROTECTION: 0
      DIFFICULTY: "hard"
      #      ENABLE_AUTOPAUSE: "TRUE"
      #      AUTOPAUSE_TIMEOUT_EST: 1800
      SNOOPER_ENABLED: "FALSE"
      ICON: "server-icon.jpg"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./mc-server/data:/data

  vpn:
    image: hwdsl2/ipsec-vpn-server
    user: root
    restart: always
    env_file:
      - ./vpn/.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    volumes:
      - ./vpn/ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro

  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    stop_grace_period: 2m
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    env_file:
      - ./vpn/.env
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=8211 # Optional but recommended
      - PLAYERS=16 # Optional but recommended
      - MULTITHREADING=false
      - RCON_ENABLED=true
      - RCON_PORT=25575
      - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
      # Enable the environment variables below if you have COMMUNITY=true
      # - SERVER_PASSWORD="worldofpals"
    volumes:
      - ./palworld:/palworld/
      - ./palworld/logs:/home/steam/Steam/logs/'

  palworld-rcon:
    image: outdead/rcon:latest
    entrypoint: ['/rcon', '-a', 'palworld:25575', '-p', '${PALWORLD_RCON_PASSWORD}']
    env_file:
      - ./rcon/.env
    profiles: ['rcon']

  vrising:
    container_name: vrising-server
    image: bjg96/vrising-server:latest
    volumes:
      - ./vrising:/data
    ports:
      - "27015:27015/udp"
      - "27016:27016/udp"
    restart: unless-stopped
    env_file:
      - ./vrising/.env
    tty: true

networks:
  boys-next-door-network:
    driver: bridge

  lavalink: # create a lavalink network you can add other containers to, to give them access to Lavalink
    name: lavalink
